### ISSUE TITLE
undefined symbol: lstat

### ISSUE THREAD

**Issue by tkcaccia** [r-lib/tzdb#26]
I report the error here below during the installation on my PC (Ubuntu OS)

Error: package or namespace load failed for ‘tzdb’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/user/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-tzdb/00new/tzdb/libs/tzdb.so':
  /home/user/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-tzdb/00new/tzdb/libs/tzdb.so: undefined symbol: lstat
Error: loading failed

**Comment by DavisVaughan** [comment]
Can you provide any other specifications on exactly what version of Ubuntu you are using?

**Comment by HowardHinnant** [comment]
I'm not sure of the cause of this error either.  But I note because it is not compile-time `lstat` must be declared. Just the definition is not found.  This seems to me to point to a build environment error.  E.g. didn't link to the proper shared lib or something like that.

**Comment by DavisVaughan** [comment]
After talking more with some others internally, our best guess is that this person has downloaded a _binary_ version of tzdb that happened to be incompatible with their system, or compiled and installed tzdb on their system and then did a system upgrade / R upgrade and just copied over the old version of the package without recompiling, and this has caused some strange incompatibility.

We are optimistic that just reinstalling tzdb from source with `pak::pak("r-lib/tzdb")` will fix this.
